package com.tire.calc.smart.app

object Constants {
    const val INCH_TO_MM = 25.4
    const val KM_IN_MM = 1000000.0
    const val MI_IN_MM = 1609344.0

    const val SAVED_WHEEL_REFERENCE_ID = 1L
    const val SAVED_WHEEL_CANDIDATE_ID = 2L

    const val SELECTED_WHEEL = "ARGUMENT_SELECTED_WHEEL"
    const val SELECTED_WHEEL_REFERENCE = "ARGUMENT_SELECTED_WHEEL_REFERENCE"
    const val SELECTED_WHEEL_CANDIDATE = "ARGUMENT_SELECTED_WHEEL_CANDIDATE"

    const val SIZE_VALUE = "ARGUMENT_SIZE_VALUE"
    const val SIZE_TYPE = "ARGUMENT_SIZE_TYPE"
    const val SIZE_RIM_HEIGHT = "ARGUMENT_SIZE_RIM_HEIGHT"
    const val SIZE_RIM_WIDTH = "ARGUMENT_SIZE_RIM_WIDTH"
    const val SIZE_RIM_ET = "ARGUMENT_SIZE_RIM_ET"
    const val SIZE_TIRE_WIDTH = "ARGUMENT_SIZE_TIRE_WIDTH"
    const val SIZE_TIRE_HEIGHT = "ARGUMENT_SIZE_TIRE_HEIGHT"

    const val REQUEST_SIZE = 42
}